TimeTagger:
  Channels:
    Ch1:
      ChannelID: 1
      TriggerLevel: 0.5  # in volts
      Deadtime: 100000  # in ps
      DelayTime: 0  # in ps
    Ch2:
      ChannelID: 2
      TriggerLevel: 0.5 # in volts
      Deadtime: 100000  # in ps
      DelayTime: 0  # in ps
    Ch3:
      ChannelID: 3
      TriggerLevel: 0.5  # in volts
      Deadtime: 100000  # in ps
      DelayTime: 0  # in ps
    Ch4:
      ChannelID: 4
      TriggerLevel: 0.5  # in volts
      Deadtime: 100000  # in ps
      DelayTime: 0  # in ps
  DataAcquisitionTime: 1  # in seconds
